version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://backend:8080
      - NEXT_PUBLIC_BASE_URL=http://backend:9000/api/v1
    volumes:
      - ./src:/app/src
      - /app/node_modules
