import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/global/theme-provider";
import { fontMontserrat } from "@/config/fonts";
import { Providers } from "@/lib/providers";
import { Toaster } from "@/components/ui/sonner";
// import { WebSocketComponent } from "@/hooks/use-websocket";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${fontMontserrat.variable} antialiased `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <Toaster richColors position="bottom-right" />
            <div className="relative flex flex-col min-h-screen">
              <main className="flex-grow">{children}</main>
            </div>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
